apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnettest-rootless
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: dotnettest-rootless
        image: cgmartinezceron/dotnettest:rootless
        ports:
        - containerPort: 80
          protocol: TCP